import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import time
from dynamap import MiniCPMSALAMock
from mcp import MobileConditioningProjector

class SimulatedTextDataset(Dataset):
    """
    Simulates a text-caption dataset yielding integer tokens of sequence length 512.
    """
    def __init__(self, num_samples=100, vocab_size=30000):
        self.num_samples = num_samples
        self.vocab_size = vocab_size

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        # Generate simulated vocabulary tokens
        return torch.randint(0, self.vocab_size, (512,))

def train_mcp_one_epoch():
    print("==================================================")
    print("        Mobile Conditioning Projector Training     ")
    print("==================================================")
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Training execution device: {device}")
    
    # 1. Instantiate the VLM Mock Backbone and our custom Ternary MCP
    vlm_dim = 1536
    dit_dim = 1024
    num_layers = 4
    
    vlm_backbone = MiniCPMSALAMock(vlm_dim=vlm_dim, num_layers=num_layers).to(device)
    mcp_projector = MobileConditioningProjector(
        vlm_dim=vlm_dim,
        dit_dim=dit_dim,
        num_layers=num_layers
    ).to(device)
    
    # Since VLM backbone parameters are frozen during typical cross-modal tuning,
    # we only train the MCP projector weights (including layer-wise fusion parameters)
    vlm_backbone.eval()
    mcp_projector.train()
    
    # 2. Setup simulated text dataloader
    dataset = SimulatedTextDataset(num_samples=32)
    dataloader = DataLoader(dataset, batch_size=4, shuffle=True)
    
    # 3. Setup optimizer for the MCP parameters
    optimizer = optim.AdamW(mcp_projector.parameters(), lr=5e-4, weight_decay=1e-3)
    
    # 4. Target Conditioning Generator (Teacher model mock)
    # Simulates target text conditioning embeddings generated by a pre-trained
    # massive T5 or CLIP text encoder: shape (B, 256, 1024)
    def get_teacher_conditioning(text_tokens):
        B, S = text_tokens.shape
        # Downsampled sequence length = S // 2 = 256
        return torch.randn(B, S // 2, dit_dim, device=text_tokens.device)

    print("Starting training loop...")
    t0 = time.time()
    
    for epoch in range(1):
        epoch_loss = 0.0
        
        for batch_idx, text_tokens in enumerate(dataloader):
            text_tokens = text_tokens.to(device)
            optimizer.zero_grad()
            
            # Extract frozen multi-layer hidden states from the VLM: list of 4 layers
            with torch.no_grad():
                vlm_hidden_states = vlm_backbone(text_tokens=text_tokens)
                
            # Extract target conditioning from the teacher
            with torch.no_grad():
                target_c = get_teacher_conditioning(text_tokens)
                
            # Forward pass through the custom ternary MCP
            # Output shape: (B, 256, 1024)
            projected_c = mcp_projector(vlm_hidden_states)
            
            # --- LOSS COMPUTATION ---
            # MSE loss between the projected ternary MCP states and teacher embeddings
            loss = torch.mean((projected_c - target_c) ** 2)
            
            # Backward pass (gradients flow through custom Straight-Through Estimators)
            loss.backward()
            
            # Gradient clipping to prevent gradient explosion in discrete weights
            torch.nn.utils.clip_grad_norm_(mcp_projector.parameters(), max_norm=1.0)
            
            optimizer.step()
            
            epoch_loss += loss.item()
            
            if (batch_idx + 1) % 4 == 0 or batch_idx == len(dataloader) - 1:
                print(f"Batch {batch_idx+1}/{len(dataloader)} | Joint Alignment Loss: {loss.item():.4f}")
                
        print(f"\n--- Epoch Summary ---")
        avg_loss = epoch_loss / len(dataloader)
        print(f"Average Epoch Alignment Loss: {avg_loss:.4f}")
        
    # 5. Save the trained checkpoint to disk
    checkpoint_path = "mcp_alignment.pth"
    print(f"\nSaving model checkpoint to: {checkpoint_path}...")
    torch.save(mcp_projector.state_dict(), checkpoint_path)
    print("Checkpoint saved successfully.")
    
    t1 = time.time()
    print(f"Completed in {t1 - t0:.2f} seconds.")
    print("==================================================")

if __name__ == "__main__":
    train_mcp_one_epoch()
